# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:49
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations

from nobetci.models import Gun, Saat, Kule, Nobetci, Grup


def kullanici_ekle():
    admin_user, created = get_user_model().objects.get_or_create(username='admin', email='admin@example.com',
                                                                 is_superuser=True, is_staff=True, is_active=True)
    admin_user.set_password('admin')
    admin_user.save()


def gunleri_ekle():
    for i in ['Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi', 'Pazar']:
        Gun.objects.create(adi='%s' % i)


def saatleri_ekle():
    for i in range(1, 25):
        Saat.objects.create(adi='%s' % i)


def kuleleri_ekle():
    for i in range(1, 8):
        kule = Kule.objects.create(adi='%s. Kule' % i)

        for gun in Gun.objects.all():
            kule.gunler.add(gun)

        for saat in Saat.objects.all():
            kule.saatler.add(saat)


def gruplari_ekle():
    for i in ['Aşçı', 'Şöför', 'Hasta']:
        Grup.objects.create(adi='%s' % i)


def nobetcileri_ekle():
    for i in range(1, 11):
        Nobetci.objects.create(adi='Nöbetçi %s' % i)


def ornet_veri_olustur(apps, schema_editor):
    kullanici_ekle()
    gunleri_ekle()
    saatleri_ekle()
    kuleleri_ekle()
    gruplari_ekle()
    nobetcileri_ekle()


class Migration(migrations.Migration):
    dependencies = [

    ]

    operations = [
        migrations.RunPython(ornet_veri_olustur)
    ]
