# Generated by Django 2.0.3 on 2018-03-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Gruplar',
                'ordering': ('adi',),
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Gün',
                'verbose_name_plural': 'Günler',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Kule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('gunler', models.ManyToManyField(blank=True, related_name='kuleler', related_query_name='kule', to='nobetci.Gun', verbose_name='Günler')),
            ],
            options={
                'verbose_name': 'Kule',
                'verbose_name_plural': 'Kuleler',
                'ordering': ('adi',),
            },
        ),
        migrations.CreateModel(
            name='Nobet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateField()),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nobetci.Gun')),
                ('kule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nobetci.Kule')),
            ],
            options={
                'verbose_name': 'Nöbet',
                'verbose_name_plural': 'Nöbetler',
            },
        ),
        migrations.CreateModel(
            name='Nobetci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('gruplar', models.ManyToManyField(blank=True, related_name='nobetciler', related_query_name='nobetci', to='nobetci.Grup', verbose_name='Gruplar')),
            ],
            options={
                'verbose_name': 'Nöbetçi',
                'verbose_name_plural': 'Nöbetçiler',
                'ordering': ('adi',),
            },
        ),
        migrations.CreateModel(
            name='Saat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Saat',
                'verbose_name_plural': 'Saatler',
                'ordering': ('-adi',),
            },
        ),
        migrations.AddField(
            model_name='nobet',
            name='nobetci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nobetci.Nobetci'),
        ),
        migrations.AddField(
            model_name='nobet',
            name='saat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nobetci.Saat'),
        ),
        migrations.AddField(
            model_name='kule',
            name='saatler',
            field=models.ManyToManyField(blank=True, related_name='kuleler', related_query_name='kule', to='nobetci.Saat', verbose_name='Saatler'),
        ),
        migrations.AddField(
            model_name='grup',
            name='gunler',
            field=models.ManyToManyField(blank=True, related_name='gruplar', related_query_name='grup', to='nobetci.Gun', verbose_name='Günler'),
        ),
        migrations.AddField(
            model_name='grup',
            name='saatler',
            field=models.ManyToManyField(blank=True, related_name='gruplar', related_query_name='grup', to='nobetci.Saat', verbose_name='Saatler'),
        ),
    ]
